

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value
    environment:
      - PORT=${PORT:-80}
      # Add database connection variables
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}